---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config: ".rubocop.yml"
ratings:
  paths:
  - "**.rb"
exclude_paths:
- config/
- spec/
- travis/
- tasks/
