language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.0
  - 2.2.4
  - 2.3.0

services:
  - cassandra

before_script:
  - cqlsh -f travis/create-schema.cql

after_script:
  - cqlsh -f travis/drop-schema.cql

script:
  - bundle exec rake spec
  - bundle exec rspec spec
